/**
 * The achievement list of Halo 3 on the Xbox 360, scraped from
 * xboxachievements.com. The source is the Wayback Machine snapshot of
 * 2025-08-15, because a Cloudflare challenge protects the live site and
 * the image host. There are 79 achievements and 1750 Gamerscore in
 * total: the base game with the Legendary, Mythic 1, Mythic 2 and Title
 * Update packs. `pack` gives the pack of each achievement.
 *
 * `img` is the local copy, under `public/assets/achievements/halo3/`, as
 * a 64x64 JPEG named by the achievement slug of the site. `sourceImg` is
 * the original URL of the copy, kept as a record. A link to `sourceImg`
 * does not work, because the host returns 403 to a request that is not
 * from a browser. `unlocked` is mock data: which achievements the
 * signed-in gamer has.
 */
export interface Halo3Achievement {
  img: string;
  sourceImg: string;
  name: string;
  description: string;
  gamerPoints: number;
  /** Whether the signed-in gamer earned it. This is mock data. */
  unlocked: boolean;
  /** "Halo 3" for the base game, else the name of the DLC pack. */
  pack: string;
}

export const HALO3_ACHIEVEMENTS: Halo3Achievement[] = [
  {
    img: "/assets/achievements/halo3/landfall.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/-4tMHw==.jpg",
    name: "Landfall",
    description: "Finish the first mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/holdout.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/-mu0jA==.jpg",
    name: "Holdout",
    description: "Finish the second mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/the-road.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+8lfdQ==.jpg",
    name: "The Road",
    description: "Finish the third mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/assault.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+imn5g==.jpg",
    name: "Assault",
    description: "Finish the fourth mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 30,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/cleansing.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+AiuUw==.jpg",
    name: "Cleansing",
    description: "Finish the fifth mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 30,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/refuge.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+ehWwA==.jpg",
    name: "Refuge",
    description: "Finish the sixth mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 30,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/last-stand.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+s9Czg==.jpg",
    name: "Last Stand",
    description: "Finish the seventh mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 40,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/the-key.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+y+6XQ==.jpg",
    name: "The Key",
    description: "Finish the eighth mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 40,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/return.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+JFXnA==.jpg",
    name: "Return",
    description: "Finish the final mission of the Campaign on Normal, Heroic, or Legendary.",
    gamerPoints: 50,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/campaign-complete-normal.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+rBeKQ==.jpg",
    name: "Campaign Complete:  Normal",
    description: "Finish the Campaign on Normal.",
    gamerPoints: 125,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/campaign-complete-heroic.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/+1Cmug==.jpg",
    name: "Campaign Complete:  Heroic",
    description: "Finish the Campaign on Heroic (unlocks achievement for Normal, if not earned).",
    gamerPoints: 125,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/campaign-complete-legendary.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/-vJNQw==.jpg",
    name: "Campaign Complete:  Legendary",
    description: "Finish the Campaign on Legendary (unlocks achievements for Normal and Heroic, if not earned).",
    gamerPoints: 125,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/iron.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPgls7c=.jpg",
    name: "Iron",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/black-eye.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPsCp7k=.jpg",
    name: "Black Eye",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/tough-luck.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPriXyo=.jpg",
    name: "Tough Luck",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/catch.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPlcsus=.jpg",
    name: "Catch",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/fog.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPt9u14=.jpg",
    name: "Fog",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/famine.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPqdQ80=.jpg",
    name: "Famine",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/thunderstorm.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP8-qDQ=.jpg",
    name: "Thunderstorm",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/tilt.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP7fUKc=.jpg",
    name: "Tilt",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/mythic.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPz+WRI=.jpg",
    name: "Mythic",
    description: "Find and claim this skull when playing on Normal, Heroic or Legendary difficulty.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/graduate.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP+VaOc=.jpg",
    name: "Graduate",
    description: "Earn 5 EXP or finish 10 games to complete the requirements for basic training (Online).",
    gamerPoints: 10,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/unsc-spartan.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP51kHQ=.jpg",
    name: "UNSC Spartan",
    description: "Earn your Sergeant rating to be recognized as a true Spartan (Online).",
    gamerPoints: 15,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/spartan-officer.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPxUmcE=.jpg",
    name: "Spartan Officer",
    description: "Advance to the Spartan Officer ranks (Online).",
    gamerPoints: 25,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/two-for-one.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPkQlxA=.jpg",
    name: "Two for One",
    description: "Score a Double Kill with a single spartan laser shot in a ranked free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/too-close-to-the-sun.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPiPc2Q=.jpg",
    name: "Too Close to the Sun",
    description: "Destroy an enemy banshee with the spartan laser or missile pod in a ranked playlist or in campaign.",
    gamerPoints: 5,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/triple-kill.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPgWiqs=.jpg",
    name: "Triple Kill",
    description: "Kill 3 enemies within 4 seconds of one another in a ranked free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/overkill.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPn2cjg=.jpg",
    name: "Overkill",
    description: "Kill 4 enemies within 4 seconds of one another in a ranked free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/lee-r-wilson-memorial.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPj6aTY=.jpg",
    name: "Lee R Wilson Memorial",
    description: "Score 5 grenade sticks in any ranked free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/were-in-for-some-chop.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPzNYA4=.jpg",
    name: "We’re in for some Chop",
    description: "Destroy an enemy vehicle with equipment in a ranked playlist or in campaign.",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/killing-frenzy.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPvXe40=.jpg",
    name: "Killing Frenzy",
    description: "Kill 10 enemies without dying in any ranked free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/steppin-razor.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPo3gx4=.jpg",
    name: "Steppin' Razor",
    description: "Score a Triple Kill with the sword in a ranked free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/mongoose-mowdown.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPjwb4M=.jpg",
    name: "Mongoose Mowdown",
    description: "Splatter an enemy with the mongoose in a ranked free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/up-close-and-personal.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPtOgkI=.jpg",
    name: "Up Close and Personal",
    description: "Kill 5 enemies by melee or assassination in a ranked free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/fear-the-pink-mist.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPlvi-c=.jpg",
    name: "Fear the Pink Mist",
    description: "Kill 5 enemies with the needler in a ranked free for all playlist or in campaign.",
    gamerPoints: 5,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/headshot-honcho.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP0tmJ0=.jpg",
    name: "Headshot Honcho",
    description: "Kill 10 enemies with headshots in a ranked free for all playlist or in campaign.",
    gamerPoints: 5,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/used-car-salesman.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP7sabs=.jpg",
    name: "Used Car Salesman",
    description: "Destroy a vehicle that has three enemies in it in a ranked playlist or in campaign.",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/marathon-man.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/-apFqg==.jpg",
    name: "Marathon Man",
    description: "Locate and access all Terminals in the Campaign.",
    gamerPoints: 40,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/mvp.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP20YVI=.jpg",
    name: "MVP",
    description: "Earn the MVP in any ranked playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/maybe-next-time-buddy.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPkakaU=.jpg",
    name: "Maybe Next Time Buddy",
    description: "Board the same vehicle within 10 seconds after being boarded in any free for all playlist (Online).",
    gamerPoints: 5,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/guerilla.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/-xK10A==.jpg",
    name: "Guerilla",
    description: "Score over 15,000 points in the Campaign meta-game on the first mission.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/demon.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/-TO8ZQ==.jpg",
    name: "Demon",
    description: "Score over 15,000 points in the Campaign meta-game on the second mission.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/cavalier.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP2HWE4=.jpg",
    name: "Cavalier",
    description: "Score over 15,000 points in the Campaign meta-game on the third mission.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/askar.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPxnoN0=.jpg",
    name: "Askar",
    description: "Score over 15,000 points in the Campaign meta-game on the fourth mission.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/exterminator.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP5GqWg=.jpg",
    name: "Exterminator",
    description: "Score over 15,000 points in the Campaign meta-game on the fifth mission.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/ranger.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP+mUfs=.jpg",
    name: "Ranger",
    description: "Score over 50,000 points in the Campaign meta-game on the sixth mission.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/vanguard.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPoEugI=.jpg",
    name: "Vanguard",
    description: "Score over 50,000 points in the Campaign meta-game on the seventh mission.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/orpheus.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPvkQpE=.jpg",
    name: "Orpheus",
    description: "Score over 15,000 points in the Campaign meta-game on the eighth mission.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/reclaimer.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPnFSyQ=.jpg",
    name: "Reclaimer",
    description: "Score over 15,000 points in the Campaign meta-game on the final mission.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Halo 3",
  },
  {
    img: "/assets/achievements/halo3/double-double.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP95i3o=.jpg",
    name: "Double Double",
    description: "On a Legendary map, get two Double Kills during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Legendary Map Pack",
  },
  {
    img: "/assets/achievements/halo3/alas-poor-yorick.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP1Ygs8=.jpg",
    name: "Alas, Poor Yorick",
    description: "On a Legendary map, get 3 Oddball melee kills during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Legendary Map Pack",
  },
  {
    img: "/assets/achievements/halo3/came-from-behind.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPy4elw=.jpg",
    name: "Came… From… Behind",
    description: "On a Legendary map, get 3 assassinations during any ranked or social match.",
    gamerPoints: 50,
    unlocked: false,
    pack: "DLC: Legendary Map Pack",
  },
  {
    img: "/assets/achievements/halo3/defend-this.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP+fblI=.jpg",
    name: "Defend This",
    description: "On a Legendary map, get a flag melee kill during any ranked or social match.",
    gamerPoints: 50,
    unlocked: false,
    pack: "DLC: Legendary Map Pack",
  },
  {
    img: "/assets/achievements/halo3/flag-dropped.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP5-lsE=.jpg",
    name: "Flag Dropped",
    description: "On a Legendary map, get 2 flag carrier kills during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Legendary Map Pack",
  },
  {
    img: "/assets/achievements/halo3/road-rage.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP3BewA=.jpg",
    name: "Road Rage",
    description: "On a Legendary map, get 5 Warthog chaingun kills during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Legendary Map Pack",
  },
  {
    img: "/assets/achievements/halo3/look-both-ways.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP-gcrU=.jpg",
    name: "Look Both Ways",
    description: "On a Legendary map, get a Splatter Spree during any ranked or social match.",
    gamerPoints: 50,
    unlocked: false,
    pack: "DLC: Legendary Map Pack",
  },
  {
    img: "/assets/achievements/halo3/hammer-time.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP4AiiY=.jpg",
    name: "Hammer Time",
    description: "On Assembly, get 5 Hammer kills during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/post-mortem.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPuxCbU=.jpg",
    name: "Post Mortem",
    description: "On Orbital, get 2 Death From the Grave medals during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/--get-the-horns.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPpR8SY=.jpg",
    name: "… Get the Horns",
    description: "On a Mythic map, get a Bulltrue medal during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/awww-too-bad.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPhw+JM=.jpg",
    name: "Awww, Too Bad",
    description: "On a Mythic map, get a Killjoy medal during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/killtacular.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPmQAAA=.jpg",
    name: "Killtacular",
    description: "On a Mythic map, get a Killtacular during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/have-fun-respawning.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPwy6-k=.jpg",
    name: "Have Fun Respawning",
    description: "On a Mythic map, get an Extermination during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/save-this-film.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP3SE2o=.jpg",
    name: "Save This Film",
    description: "On a Mythic map, get a Perfection medal during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/delicious-brains.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP-zGt8=.jpg",
    name: "Delicious Brains",
    description: "On a Mythic map, infect 2 humans during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/zombie-repeller.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP4T4kw=.jpg",
    name: "Zombie Repeller",
    description: "On a Mythic map, kill 2 Zombies during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/tank-dropper.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP009kI=.jpg",
    name: "Tank Dropper",
    description: "On any Mythic map, get a kill on another player while in monitor mode.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/assembly-skull.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPzUDtE=.jpg",
    name: "Assembly Skull",
    description: "On Assembly, find the hidden skull.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/orbital-skull.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPkJ+c8=.jpg",
    name: "Orbital Skull",
    description: "On Orbital, find the hidden skull.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/sandbox-skull.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPjpAVw=.jpg",
    name: "Sandbox Skull",
    description: "On Sandbox, find the hidden skull.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 1",
  },
  {
    img: "/assets/achievements/halo3/pull-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPuiYd8=.jpg",
    name: "Pull",
    description: "On Citadel, get a Shotgun Spree during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 2",
  },
  {
    img: "/assets/achievements/halo3/blades-of-fury.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPpCmUw=.jpg",
    name: "Blades of Fury",
    description: "On Heretic, get a Sword Spree during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 2",
  },
  {
    img: "/assets/achievements/halo3/ghost-patrol.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPhjkPk=.jpg",
    name: "Ghost Patrol",
    description: "On Longshore, get 3 kills with a Ghost during any ranked or social match.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 2",
  },
  {
    img: "/assets/achievements/halo3/citadel-skull.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP9q4xA=.jpg",
    name: "Citadel Skull",
    description: "On Citadel, find the hidden skull.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 2",
  },
  {
    img: "/assets/achievements/halo3/heretic-skull.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP1L6qU=.jpg",
    name: "Heretic Skull",
    description: "On Heretic, find the hidden skull.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 2",
  },
  {
    img: "/assets/achievements/halo3/longshore-skull.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPyrEjY=.jpg",
    name: "Longshore Skull",
    description: "On Longshore, find the hidden skull.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 2",
  },
  {
    img: "/assets/achievements/halo3/vidmaster-challenge-brainpan.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPrICOk=.jpg",
    name: "Vidmaster Challenge: Brainpan",
    description: "Find all the hidden skulls on the Mythic maps.",
    gamerPoints: 25,
    unlocked: false,
    pack: "DLC: Mythic Map Pack 2",
  },
  {
    img: "/assets/achievements/halo3/vidmaster-challenge-annual.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UP6Zc+k=.jpg",
    name: "Vidmaster Challenge: Annual",
    description: "After 9/25/08, complete Halo on 4-player Legendary LIVE co-op, with Iron, and everyone in Ghosts.",
    gamerPoints: 0,
    unlocked: false,
    pack: "DLC: Title Update",
  },
  {
    img: "/assets/achievements/halo3/vidmaster-challenge-lightswitch.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPrbYIM=.jpg",
    name: "Vidmaster Challenge: Lightswitch",
    description: "Get to the rank of Lieutenant in any playlist in the new EXP progression system.",
    gamerPoints: 0,
    unlocked: false,
    pack: "DLC: Title Update",
  },
  {
    img: "/assets/achievements/halo3/vidmaster-challenge-7-on-7.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/274/UPs7mBA=.jpg",
    name: "Vidmaster Challenge: 7 on 7",
    description: "Enter into any ranked or social playlist with 7 EXP on the 7th of the month.",
    gamerPoints: 0,
    unlocked: false,
    pack: "DLC: Title Update",
  },
];
