/**
 * Midnight Club: Los Angeles (Xbox 360) achievement list, scraped from
 * xboxachievements.com via the Wayback Machine snapshot of 2024-11-27 (the
 * live site and image host sit behind a Cloudflare challenge). 55
 * achievements, 1250 Gamerscore in total: the base game plus the South
 * Central pack, distinguished by `pack`.
 *
 * `img` is the local copy under `public/assets/achievements/mcla/` (64×64
 * JPEG, named by the site's achievement slug); `sourceImg` is the original
 * URL it was copied from, kept for provenance. It cannot be hot-linked: the
 * host returns 403 to non-browser requests. `unlocked` is mock: which of
 * these the signed-in gamer has earned.
 */
export interface MclaAchievement {
  img: string;
  sourceImg: string;
  name: string;
  description: string;
  gamerPoints: number;
  /** Whether the signed-in gamer has earned it (mock). */
  unlocked: boolean;
  /** "Midnight Club: Los Angeles" for the base game, otherwise the DLC pack name. */
  pack: string;
}

export const MCLA_ACHIEVEMENTS: MclaAchievement[] = [
  {
    img: "/assets/achievements/mcla/wanted-man.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPi9OJo=.jpg",
    name: "Wanted Man",
    description: "Pull over while the police are in 'pull over' mode, then drive away during the ticketing cutscene.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/out-on-bail.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP8N48o=.jpg",
    name: "Out On Bail",
    description: "Evade the police successfully when they are in pursuit.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/neither-bird-nor-plane.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP504pY=.jpg",
    name: "Neither Bird nor Plane",
    description: "Travel 1020 feet in a single jump.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/jordan-jumpman.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/+L12TA==.jpg",
    name: "Jordan Jumpman",
    description: "Spend more than 10 minutes in the air. Brought to you by JORDAN BRAND.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/unicycle.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPoFyOA=.jpg",
    name: "Unicycle",
    description: "Drive a cumulative total of 50 miles while doing a wheelie on a motorcycle.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/just-get-a-motorcycle.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP0f02M=.jpg",
    name: "Just Get A Motorcycle",
    description: "In a car, drive a cumulative total of 50 miles on 2 wheels.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/hear-me-roar-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPxm0j8=.jpg",
    name: "Hear me Roar!",
    description: "Unlock Level 3 ROAR.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/anger-management.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP8+2tY=.jpg",
    name: "Anger Management",
    description: "Unlock Level 3 AGRO.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/set-to-stun.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP2GKqw=.jpg",
    name: "Set To Stun",
    description: "Unlock Level 3 EMP.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/zoning-out.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPgkwVU=.jpg",
    name: "Zoning Out",
    description: "Unlock Level 3 ZONE.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/in-the-lap-of.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP35Nks=.jpg",
    name: "In the Lap of…",
    description: "Beat the Luxury Champ.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/name-that-tune-r-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPnEOcY=.jpg",
    name: "Name that Tune ( r )",
    description: "Beat the Tuner Champ.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/worlds-strongest.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP+nIxk=.jpg",
    name: "World's Strongest",
    description: "Beat the Muscle Champ.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/two-wheels-of-fury.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPwZztg=.jpg",
    name: "Two Wheels of Fury",
    description: "Beat the Motorcycle Champ.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/how-exotic.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP7eIkU=.jpg",
    name: "How Exotic",
    description: "Beat the Exotic Champ.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/the-basics.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPlu+RU=.jpg",
    name: "The Basics",
    description: "Complete one of the missions you receive in the mission log.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/whats-a-speed-limit-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP4ywdg=.jpg",
    name: "What's a Speed Limit?",
    description: "Win 15 dynamic freeway races.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/streaker.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPiOAYY=.jpg",
    name: "Streaker",
    description: "Win 5 races in a row offline.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/winning-with-less.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPwTyG0=.jpg",
    name: "Winning With Less",
    description: "Win 10 races on a motorcycle.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/go-on-green.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP3zMP4=.jpg",
    name: "Go on Green",
    description: "Win 15 Red Light Races.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/destroyer-of-worlds.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPqvCDM=.jpg",
    name: "Destroyer of Worlds",
    description: "Successfully destroy 15 opponent vehicles using the Payback vehicle at the Beaches garage.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/here-for-a-pickup.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/+CSPgw==.jpg",
    name: "Here for a Pickup",
    description: "Successfully deliver 15 vehicles out of the Hollywood garage.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/father-time.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-6dtzw==.jpg",
    name: "Father Time",
    description: "Completely unlock a time trial by completing all 3 missions.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/uncle-time.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-YZkeg==.jpg",
    name: "Uncle Time",
    description: "Finish the first mission for each of the 4 time trials.",
    gamerPoints: 20,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/competitive-glory.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-Gac6Q==.jpg",
    name: "Competitive Glory",
    description: "Win each of the 4 tournaments at least one time.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/its-how-you-play-the-game.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPo28fw=.jpg",
    name: "It's How You Play The Game",
    description: "Finish 300 offline races. Winning is not required.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/the-winner.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP-rBuI=.jpg",
    name: "The Winner",
    description: "Win 180 offline races.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/rags-to-riches.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP7tG1k=.jpg",
    name: "Rags To Riches",
    description: "Have $1 million dollars in the bank while playing in Los Angeles.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/have-car-will-travel.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPtP8KA=.jpg",
    name: "Have Car, Will Travel",
    description: "Drive a total of 5,000 miles, including any miles driven online or offline.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/getting-off-the-bench.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP+UGgU=.jpg",
    name: "Getting Off the Bench",
    description: "Enter an online cruise and join a proposed race.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/who-made-this-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP21E7A=.jpg",
    name: "Who Made This?",
    description: "Enter a Race Editor Race online.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/saving-los-angeles.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPz-K-A=.jpg",
    name: "Saving Los Angeles",
    description: "Enter the Race Editor, create a race, and then save it.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/paparazzi.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPldwAk=.jpg",
    name: "Paparazzi",
    description: "Save 16 photos to your photo album.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/t-mobile-myfaves.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-R+dtQ==.jpg",
    name: "T-Mobile myFaves",
    description: "Join an online game with 5 of your friends. Stay Connected with MyFaves from T-Mobile.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/turn-in-the-work.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPqcMS8=.jpg",
    name: "Turn in the Work",
    description: "Submit a vehicle to Rate My Ride.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/everyones-a-critic.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPt8ybw=.jpg",
    name: "Everyone's a Critic",
    description: "Rate 25 rides online.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/crossing-the-line.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/+gWGNg==.jpg",
    name: "Crossing the Line",
    description: "Finish 50 races online.",
    gamerPoints: 20,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/master-thief.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPzMEuw=.jpg",
    name: "Master Thief",
    description: "Steal 80 flags while playing Capture the Flag or other battle matches.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/postman.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP0s6n8=.jpg",
    name: "Postman",
    description: "Deliver 100 flags in Capture the Flag or other battle matches.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/ranking-up.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPgX+Ek=.jpg",
    name: "Ranking Up",
    description: "Win 20 ranked matches online.",
    gamerPoints: 30,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/where-in-the-world-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP4L-nE=.jpg",
    name: "Where in the World?",
    description: "Find half of the collectables in Los Angeles.",
    gamerPoints: 10,
    unlocked: true,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/waldos-still-missing.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-P9lJg==.jpg",
    name: "Waldo's Still Missing",
    description: "Find all the collectables in Los Angeles.",
    gamerPoints: 40,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/retire-the-master.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/+cR3EA==.jpg",
    name: "Retire the Master",
    description: "Beat the City Champ.",
    gamerPoints: 50,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/mild-dedication.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-BmADg==.jpg",
    name: "Mild Dedication",
    description: "In Goal Attack, complete every goal for one race.",
    gamerPoints: 10,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/true-dedication.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-fl4nQ==.jpg",
    name: "True Dedication",
    description: "All Goal attacks must be unlocked and every goal for every race completed.",
    gamerPoints: 100,
    unlocked: false,
    pack: "Midnight Club: Los Angeles",
  },
  {
    img: "/assets/achievements/mcla/goin-south.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UP-SOUs=.jpg",
    name: "Goin' South",
    description: "Meet the South Central Mechanic.",
    gamerPoints: 10,
    unlocked: true,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/south-central-test-drive.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPpw0rI=.jpg",
    name: "South Central Test Drive",
    description: "Take 1 South Central vehicle out for a test drive.",
    gamerPoints: 10,
    unlocked: true,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/big-ballin-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPhR2wc=.jpg",
    name: "Big Ballin'",
    description: "Win 10 races in an SUV.",
    gamerPoints: 20,
    unlocked: false,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/low-ballin-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPuQKiE=.jpg",
    name: "Low Ballin'",
    description: "Win 10 races in a Low Rider.",
    gamerPoints: 20,
    unlocked: false,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/sign-here.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPmxI5Q=.jpg",
    name: "Sign Here",
    description: "Complete 10 deliveries in South Central.",
    gamerPoints: 20,
    unlocked: false,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/easier-than-the-hills.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPt2zwk=.jpg",
    name: "Easier than the Hills",
    description: "Complete the South Central tournament.",
    gamerPoints: 20,
    unlocked: false,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/money-for-nothing.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-z6UAA==.jpg",
    name: "Money for nothing",
    description: "Complete the South Central Wager Mission.",
    gamerPoints: 20,
    unlocked: false,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/brother-time.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/+px-+Q==.jpg",
    name: "Brother Time",
    description: "Complete the 3 missions for the South Central time trial.",
    gamerPoints: 20,
    unlocked: false,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/been-there-done-that.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/UPvWCW8=.jpg",
    name: "Been there, Done that",
    description: "Finish the South Central career.",
    gamerPoints: 50,
    unlocked: false,
    pack: "DLC: South Central",
  },
  {
    img: "/assets/achievements/mcla/gooooaaaaalllll-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/372/-t5skw==.jpg",
    name: "GOOOOAAAAALLLLL!!!!!",
    description: "Finish all South Central Goal Attacks.",
    gamerPoints: 60,
    unlocked: false,
    pack: "DLC: South Central",
  },
];
