/**
 * The achievement list of Call of Duty: Modern Warfare 3 on the Xbox
 * 360, scraped from xboxachievements.com. The source is the Wayback
 * Machine snapshot of 2024-02-22, because a Cloudflare challenge
 * protects the live site and the image host. There are 76 achievements
 * and 1610 Gamerscore in total.
 *
 * `img` is the local copy, under `public/assets/achievements/mw3/`, as a
 * 64x64 JPEG named by the achievement slug of the site. `sourceImg` is
 * the original URL of the copy, kept as a record. A link to `sourceImg`
 * does not work, because the host returns 403 to a request that is not
 * from a browser. `unlocked` is mock data: which achievements the
 * signed-in gamer has.
 */
export interface Mw3Achievement {
  img: string;
  sourceImg: string;
  name: string;
  description: string;
  gamerPoints: number;
  /** Whether the signed-in gamer earned it. This is mock data. */
  unlocked: boolean;
}

export const MW3_ACHIEVEMENTS: Mw3Achievement[] = [
  {
    img: "/assets/achievements/mw3/back-in-the-fight.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP0i1ZU=.jpg",
    name: "Back in the Fight",
    description: "Start the Single Player Campaign on any difficulty.",
    gamerPoints: 5,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/too-big-to-fail.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPzAOM0=.jpg",
    name: "Too Big to Fail",
    description: "Destroy the Jamming Tower. Complete \"Black Tuesday\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/wet-work.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP+aJe8=.jpg",
    name: "Wet Work",
    description: "Take back New York Harbor. Complete \"Hunter Killer\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/carpe-diem.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP1M4kg=.jpg",
    name: "Carpe Diem",
    description: "Escape the mountain safe house. Complete \"Persona Non Grata\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/frequent-flyer.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPrWOEA=.jpg",
    name: "Frequent Flyer",
    description: "Defend the Russian President. Complete \"Turbulence\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/up-to-no-good.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPgZx6M=.jpg",
    name: "Up to No Good",
    description: "Infiltrate the village. Complete \"Back on the Grid\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/one-way-ticket.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPmOMKk=.jpg",
    name: "One Way Ticket",
    description: "Make it to Westminster. Complete \"Mind the Gap\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/welcome-to-ww3.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPvYNoU=.jpg",
    name: "Welcome to WW3",
    description: "Save the US Vice President. Complete \"Goalpost\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/sandstorm-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP+YMCQ=.jpg",
    name: "Sandstorm!",
    description: "Assault the shipping company. Complete \"Return to Sender\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/back-seat-driver.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPrPAAQ=.jpg",
    name: "Back Seat Driver",
    description: "Track down Volk. Complete \"Bag and Drag\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/we-ll-always-have-paris.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP563Xw=.jpg",
    name: "We'll Always Have Paris",
    description: "Escape Paris with Volk. Complete \"Iron Lady\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/vive-la-rvolution-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPo4zhY=.jpg",
    name: "Vive la Révolution!",
    description: "Reach the church. Complete \"Eye of the Storm\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/requiem.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPxZwQI=.jpg",
    name: "Requiem",
    description: "Escape the city. Complete \"Blood Brothers\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/storm-the-castle.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPn7Kvs=.jpg",
    name: "Storm the Castle",
    description: "Discover Makarov's next move. Complete \"Stronghold\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/bad-first-date.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP9t6-0=.jpg",
    name: "Bad First Date",
    description: "Find the girl. Complete \"Scorched Earth\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/diamond-in-the-rough.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPpW+cs=.jpg",
    name: "Diamond in the Rough",
    description: "Rescue the Russian President. Complete \"Down the Rabbit Hole\" on any difficulty.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/the-big-apple.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPtD2oE=.jpg",
    name: "The Big Apple",
    description: "Complete \"Black Tuesday\" and \"Hunter Killer\" on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/out-of-the-frying-pan.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPhuyDo=.jpg",
    name: "Out of the Frying Pan…",
    description: "Complete \"Persona Non Grata\", \"Turbulence\", and \"Back on the Grid\" on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/payback.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPiAPmw=.jpg",
    name: "Payback",
    description: "Complete \"Mind the Gap\", \"Goalpost\", and \"Return to Sender\" on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/city-of-lights.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP5r9kY=.jpg",
    name: "City of Lights",
    description: "Complete \"Bag and Drag\" and \"Iron Lady\" on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/the-darkest-hour.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP4U6qE=.jpg",
    name: "The Darkest Hour",
    description: "Complete \"Eye of the Storm\", \"Blood Brothers\", and \"Stronghold\" on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/this-is-the-end.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP7hMXg=.jpg",
    name: "This is the End",
    description: "Complete \"Scorched Earth\", \"Down the Rabbit Hole\", and \"Dust to Dust\" on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/who-dares-wins.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPxb1Mk=.jpg",
    name: "Who Dares Wins",
    description: "Complete the campaign on any difficulty.",
    gamerPoints: 40,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/the-best-of-the-best.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPli0zQ=.jpg",
    name: "The Best of the Best",
    description: "Complete the campaign on Hardened or Veteran difficulty.",
    gamerPoints: 100,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/strike-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPgb0mg=.jpg",
    name: "Strike!",
    description: "Kill 5 enemies with a single grenade in Single Player or Special Ops.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/jack-the-ripper.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP9007k=.jpg",
    name: "Jack the Ripper",
    description: "Melee 5 enemies in a row in Single Player or Special Ops.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/informant.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP8D3CA=.jpg",
    name: "Informant",
    description: "Collect 22 Intel Items.",
    gamerPoints: 20,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/scout-leader.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP7jJLM=.jpg",
    name: "Scout Leader",
    description: "Collect 46 Intel Items.",
    gamerPoints: 35,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/this-is-my-boomstick.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP8Byes=.jpg",
    name: "This Is My Boomstick",
    description: "Kill 30 enemies with the XM25 in \"Black Tuesday.\"",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/what-goes-up.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP27LFo=.jpg",
    name: "What Goes Up…",
    description: "Destroy all the choppers with only the UGV's grenade launcher in \"Persona Non Grata.\"",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/for-whom-the-shell-tolls.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP98wMc=.jpg",
    name: "For Whom the Shell Tolls",
    description: "Destroy all targets during the mortar sequence with only 4 shells in \"Back on the Grid.\"",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/kill-box.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPxTx7c=.jpg",
    name: "Kill Box",
    description: "Kill 20 enemies with the Chopper Gunner in a single run in \"Return to Sender.\"",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/danger-close.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP+LDtU=.jpg",
    name: "Danger Close",
    description: "Take down a chopper with an AC-130 smoke grenade in \"Bag and Drag.\"",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/mnage--trois.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP-tKnY=.jpg",
    name: "Ménage à Trois",
    description: "Destroy 3 tanks with a single 105mm shot in \"Iron Lady.\"",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/nein.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP3MI8M=.jpg",
    name: "Nein",
    description: "Kill 9 enemies with A-10 strafing runs in \"Scorched Earth.\"",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/50-50.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPkO8SI=.jpg",
    name: "50/50",
    description: "Complete a Special Ops Mission Mode game with the same number of kills as your partner.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/birdie.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP6NE24=.jpg",
    name: "Birdie",
    description: "Kill 2 enemy helicopters without getting hit in a Special Ops Survival game.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/serrated-edge.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPvaI04=.jpg",
    name: "Serrated Edge",
    description: "Finish a Juggernaut with a knife in Special Ops.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/arms-dealer.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPsv+Jc=.jpg",
    name: "Arms Dealer",
    description: "Buy all items from the Survival Weapon Armory.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/danger-zone.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPw14xQ=.jpg",
    name: "Danger Zone",
    description: "Buy all items from the Survival Air Support Armory.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/defense-spending.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP-0EjI=.jpg",
    name: "Defense Spending",
    description: "Buy all items from the Survival Equipment Armory.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/get-rich-or-die-trying.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPy1Ip8=.jpg",
    name: "Get Rich or Die Trying",
    description: "Have $50,000 current balance in a Special Ops Survival game.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/i-live.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPtBz0o=.jpg",
    name: "I Live",
    description: "Survive 1 wave in a Special Ops Survival game.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/survivor.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPs8xmY=.jpg",
    name: "Survivor",
    description: "Reach Wave 10 in each mission of Special Ops Survival mode.",
    gamerPoints: 20,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/unstoppable.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPn5PzA=.jpg",
    name: "Unstoppable",
    description: "Reach Wave 15 in each mission of Special Ops Survival mode.",
    gamerPoints: 40,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/no-assistance-required.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPws21A=.jpg",
    name: "No Assistance Required",
    description: "Complete a Special Ops Mission Mode game on Hardened or Veteran with no player getting downed.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/brag-rags.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPysGts=.jpg",
    name: "Brag Rags",
    description: "Earn 1 star in Special Ops Mission Mode.",
    gamerPoints: 10,
    unlocked: true,
  },
  {
    img: "/assets/achievements/mw3/tactician.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPqhN9k=.jpg",
    name: "Tactician",
    description: "Earn 1 star in each mission of Special Ops Mission Mode.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/overachiever.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPpPwY8=.jpg",
    name: "Overachiever",
    description: "Earn 48 stars in Special Ops Mission Mode.",
    gamerPoints: 40,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/flight-attendant.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/s1.jpg",
    name: "Flight Attendant",
    description: "Kill all 5 enemies during the zero-g sequence in \"Turbulence.\"",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/shotgun-diplomacy.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPvrD5k=.jpg",
    name: "Shotgun Diplomacy",
    description: "Complete the Special Ops mission \"Negotiator\" on any difficulty.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/not-on-my-watch.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPoL9wo=.jpg",
    name: "Not on My Watch",
    description: "Rescue all the hostages in the Special Ops mission \"Negotiator.\"",
    gamerPoints: 35,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/skilled-negotiator.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPgq-r8=.jpg",
    name: "Skilled Negotiator",
    description: "Complete the Special Ops mission \"Negotiator\" on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/slippery-slope.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPnKBiw=.jpg",
    name: "Slippery Slope",
    description: "Complete the \"Black Ice\" Special Ops mission on any difficulty.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/a-bakers-dozen.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPxo7dU=.jpg",
    name: "A Baker's Dozen",
    description: "Run over and kill 13 enemies with the snowmobile in the \"Black Ice\" Special Ops mission.",
    gamerPoints: 35,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/ice-in-your-veins.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP2IFUY=.jpg",
    name: "Ice in Your Veins",
    description: "Complete the \"Black Ice\" Special Ops mission on Veteran difficulty.",
    gamerPoints: 35,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/don-t-tread-on-me.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP+pHPM=.jpg",
    name: "Don't Tread on Me",
    description: "Complete the \"Iron Clad\" Special Ops mission on any difficulty.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/high-roller.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP5J5GA=.jpg",
    name: "High Roller",
    description: "Complete the \"Iron Clad\" Special Ops mission on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/not-a-scratch.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP1u8G4=.jpg",
    name: "Not a Scratch",
    description: "Finish with your tank at full health in the \"Iron Clad\" Special Ops mission.",
    gamerPoints: 35,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/one-four-one.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPyOCP0=.jpg",
    name: "One-Four-One",
    description: "Complete the \"Kill Switch\" Special Ops mission on any difficulty.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/helipocalypse.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP8w5Tw=.jpg",
    name: "Helipocalypse",
    description: "Destroy 6 helicopters in the \"Kill Switch\" Special Ops mission.",
    gamerPoints: 30,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/empressive-.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP0R7Ik=.jpg",
    name: "EMPressive...",
    description: "Complete the \"Kill Switch\" Special Ops mission on Veteran difficulty.",
    gamerPoints: 30,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/stay-frosty.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP1k9ts=.jpg",
    name: "Stay Frosty",
    description: "Complete the \"Arctic Recon\" Special Ops mission on any difficulty.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/sub-zero.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPyEDkg=.jpg",
    name: "Sub Zero",
    description: "Complete the \"Arctic Recon\" Special Ops mission on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/dr0n3d.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP6lB-0=.jpg",
    name: "dr0n3d",
    description: "Complete the \"Arctic Recon\" Special Ops mission in under 3:30.",
    gamerPoints: 35,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/apex.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPykk5M=.jpg",
    name: "Apex",
    description: "Complete the \"Vertigo\" Special Ops mission on any difficulty.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/pinnacle.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP6FmiY=.jpg",
    name: "Pinnacle",
    description: "Complete the \"Vertigo\" Special Ops mission on Veteran difficulty.",
    gamerPoints: 20,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/flyswatter.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP1EawA=.jpg",
    name: "Flyswatter",
    description: "Destroy all helicopters in the \"Vertigo\" Special Ops mission.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/to-jugger-or-to-jugger-naut.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP5jfw4=.jpg",
    name: "To Jugger or to Jugger-Naut",
    description: "Kill all juggernauts after they land on Veteran difficulty in the \"Vertigo\" Special Ops mission.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/handle-with-care.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP+Dh50=.jpg",
    name: "Handle with Care",
    description: "Complete the \"Special Delivery\" Special Ops mission on any difficulty.",
    gamerPoints: 10,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/deliver-this.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPys2DE=.jpg",
    name: "Deliver This",
    description: "Complete the \"Special Delivery\" Special Ops mission on Veteran difficulty.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/-discriminating-buyer.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP6N0YQ=.jpg",
    name: "Discriminating Buyer",
    description: "Use exactly one of each care package in the \"Special Delivery\" Special Ops mission.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/untouchable.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UP9tKRc=.jpg",
    name: "Untouchable",
    description: "Use only one self revive care package in the \"Special Delivery\" Special Ops mission.",
    gamerPoints: 25,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/siege.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPrPwu4=.jpg",
    name: "Siege",
    description: "Complete the \"Light 'Em Up\" Special Ops mission on any difficulty.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/-lights-out.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPsvOn0=.jpg",
    name: "Lights Out",
    description: "Complete the \"Light 'Em Up\" Special Ops mission on Veteran difficulty.",
    gamerPoints: 15,
    unlocked: false,
  },
  {
    img: "/assets/achievements/mw3/-deer-in-the-headlights.jpg",
    sourceImg: "https://img.xboxachievements.com/images/achievements/1372/UPkOM8g=.jpg",
    name: "Deer in the Headlights",
    description: "Stab five stunned enemies in a row in the \"Light 'Em Up\" Special Ops mission.",
    gamerPoints: 45,
    unlocked: false,
  },
];
